fixdt32_8 = Simulink.NumericType;
fixdt32_8.DataTypeMode = 'Fixed-point: binary point scaling';
fixdt32_8.Signedness = 'Unsigned';
fixdt32_8.WordLength = 32;
fixdt32_8.FractionLength = 8;
fixdt32_8.IsAlias = 1;
fixdt32_8.DataScope = 'Exported';
fixdt32_8.HeaderFile = 'custom.h';
fixdt32_8.Description ='This data type is created by Simulink.NumericType.';
